/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductOption = {
  _type: "productOption";
  name?: string;
  values?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ScentFamilyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "scentFamily";
};

export type OccasionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "occasion";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  notes?: string;
  price?: number;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  category?: CategoryReference;
  scentFamily?: ScentFamilyReference;
  occasion?: OccasionReference;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
};

export type Occasion = {
  _id: string;
  _type: "occasion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ScentFamily = {
  _id: string;
  _type: "scentFamily";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductOption
  | SanityImageAssetReference
  | CategoryReference
  | ScentFamilyReference
  | OccasionReference
  | Product
  | Occasion
  | Slug
  | ScentFamily
  | Category
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../website/src/sanity/queries.ts
// Variable: PRODUCT_FILTER_OPTIONS_QUERY
// Query: {  "categories": *[_type == "category" && defined(slug.current)] | order(title asc) { "id": slug.current, "label": title },  "scentFamilies": *[_type == "scentFamily" && defined(slug.current)] | order(title asc) { "id": slug.current, "label": title },  "occasions": *[_type == "occasion" && defined(slug.current)] | order(title asc) { "id": slug.current, "label": title }}
export type PRODUCT_FILTER_OPTIONS_QUERY_RESULT = {
  categories: Array<{
    id: string | null;
    label: string | null;
  }>;
  scentFamilies: Array<{
    id: string | null;
    label: string | null;
  }>;
  occasions: Array<{
    id: string | null;
    label: string | null;
  }>;
};

// Source: ../website/src/sanity/queries.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0] {  _id,  name,  "slug": slug.current,  description,  notes,  price,  images[]{    alt,    asset,    crop,    hotspot  },  "category": category->slug.current,  "scentFamily": scentFamily->slug.current,  "occasion": occasion->slug.current,  options[]{    _key,    name,    values  }}
export type PRODUCT_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  notes: string | null;
  price: number | null;
  images: Array<{
    alt: string | null;
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  category: string | null;
  scentFamily: string | null;
  occasion: string | null;
  options: Array<{
    _key: string;
    name: string | null;
    values: Array<string> | null;
  }> | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "categories": *[_type == "category" && defined(slug.current)] | order(title asc) { "id": slug.current, "label": title },\n  "scentFamilies": *[_type == "scentFamily" && defined(slug.current)] | order(title asc) { "id": slug.current, "label": title },\n  "occasions": *[_type == "occasion" && defined(slug.current)] | order(title asc) { "id": slug.current, "label": title }\n}': PRODUCT_FILTER_OPTIONS_QUERY_RESULT;
    '\n  *[_type == "product" && slug.current == $slug][0] {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  notes,\n  price,\n  images[]{\n    alt,\n    asset,\n    crop,\n    hotspot\n  },\n  "category": category->slug.current,\n  "scentFamily": scentFamily->slug.current,\n  "occasion": occasion->slug.current,\n  options[]{\n    _key,\n    name,\n    values\n  }\n}\n': PRODUCT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
